import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../analytics/migration/worker.mjs';
const origin='https://khairuladamm1993-web.github.io';
function db(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../analytics/original/drizzle/0000_loose_northstar.sql',import.meta.url),'utf8'));return{sql,prepare(query){return{bind(...args){return{query,args};}}},async batch(rows){sql.exec('BEGIN');try{for(const r of rows)sql.prepare(r.query).run(...r.args);sql.exec('COMMIT');}catch(e){sql.exec('ROLLBACK');throw e;}}};}
const request=(counts,from=origin)=>new Request('https://migration.example.workers.dev/api/anonymous-counts',{method:'POST',headers:{origin:from,'content-type':'application/json'},body:JSON.stringify({counts})});
test('staged collector differs from tested collector only in fixed metric and route allowlists',()=>{let added=readFileSync(new URL('../analytics/migration/collector.mjs',import.meta.url),'utf8');const original=readFileSync(new URL('../analytics/original/analytics/collector.mjs',import.meta.url),'utf8');added=added.replace("'about','contact','resume'];","'about','contact'];").replace(/  category:.*\n  module:.*\n  quiz_start:.*\n/,'');assert.equal(added,original);});
test('all five categories, ten modules and quiz counters write and read through existing aggregate schema',async()=>{const DB=db();const rows=[...['practical','ebook','corridor','future','news'].map(b=>['category',b,1]),...['df8b_inspection','df8b_electrical','df8b_brake','stabilizer','ballast','tamping','gmc48','ccpg500a','eloco','cr200j'].map(b=>['module',b,1]),['quiz_start','all',1],['quiz_complete','all',1],['view','resume',1],['funnel','portfolio',1]];assert.equal((await worker.fetch(request(rows),{DB})).status,204);const stored=DB.sql.prepare('SELECT metric,bucket,value FROM anonymous_daily_totals').all();assert.equal(stored.length,rows.length);for(const [metric,bucket,value] of rows)assert(stored.some(r=>r.metric===metric&&r.bucket===bucket&&r.value===value));for(const query of readFileSync(new URL('../analytics/backend/dashboard.sql',import.meta.url),'utf8').split(';').filter(s=>s.trim()))assert(Array.isArray(DB.sql.prepare(query).all()));DB.sql.close();});
test('extended collector rejects arbitrary identity buckets, extra fields and unapproved origins',async()=>{const DB=db();for(const rows of [[['module','visitor-name',1]],[['email','someone@example.com',1]],[['quiz_complete','all',1,16]]])assert.equal((await worker.fetch(request(rows),{DB})).status,400);assert.equal((await worker.fetch(request([['category','news',1]],'https://unapproved.example'),{DB})).status,403);assert.equal(DB.sql.prepare('SELECT count(*) n FROM anonymous_daily_totals').get().n,0);DB.sql.close();});
test('GPC still disables extended metrics and coarse country absence cannot block them',async()=>{const DB=db();let req=request([['quiz_start','all',1]]);req.headers.set('Sec-GPC','1');assert.equal((await worker.fetch(req,{DB})).status,204);assert.equal(DB.sql.prepare('SELECT count(*) n FROM anonymous_daily_totals').get().n,0);req=request([['visits','all',1],['quiz_start','all',1]]);Object.defineProperty(req,'cf',{get(){throw Error('unavailable');}});assert.equal((await worker.fetch(req,{DB})).status,204);assert.equal(DB.sql.prepare("SELECT count(*) n FROM anonymous_daily_totals WHERE metric='country'").get().n,0);DB.sql.close();});
