const {test,afterEach}=require('node:test');const openPages=[];afterEach(()=>{for(const d of openPages.splice(0))d.window.close();});const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const crypto=require('node:crypto');
const {JSDOM,ResourceLoader,VirtualConsole}=require(process.env.RAILWAY_JSDOM||'jsdom');
const root=path.resolve(__dirname,'..'),origin='https://khairuladamm1993-web.github.io',prefix='/khairul-adam-ecrlrailway-malaysia-portfolio/';
const code=fs.readFileSync(path.join(root,'assets/questions.js'),'utf8'),ctx={window:{}};vm.runInNewContext(code,ctx);const mods=ctx.window.RailwayModules;const core=require('../assets/quiz-core.js');
class LocalResources extends ResourceLoader{fetch(url){const u=new URL(url);if(u.origin!==origin)throw Error('Unexpected resource origin');const p=path.join(root,u.pathname.slice(prefix.length));return Promise.resolve(fs.readFileSync(p));}}
async function page(file,{local={},session={},extension=false,dnt=false}={}){
 const sent=[],errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!e.message.includes('navigation'))errors.push(e.message);});
 let html=fs.readFileSync(path.join(root,file.split('#')[0]),'utf8');if(extension)html=html.replace('content="pending"','content="enabled"');
 const dom=new JSDOM(html,{url:origin+prefix+file,runScripts:'dangerously',resources:new LocalResources(),pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.scrollBy=()=>{};w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.IntersectionObserver=class{observe(){}};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.confirm=()=>true;w.fetch=async(url,opts)=>{sent.push({url,opts,body:JSON.parse(opts.body)});return{ok:true,status:204};};Object.entries(local).forEach(([k,v])=>w.localStorage.setItem(k,v));Object.entries(session).forEach(([k,v])=>w.sessionStorage.setItem(k,v));Object.defineProperty(w.navigator,'doNotTrack',{value:dnt?'1':'0'});for(const key of ['geolocation','permissions'])Object.defineProperty(w.navigator,key,{get(){throw Error('Forbidden API '+key);}});}});
 openPages.push(dom);await new Promise(resolve=>dom.window.addEventListener('load',resolve));await settle();
 assert.deepEqual(errors,[]);return {dom,w:dom.window,d:dom.window.document,sent,errors,close:()=>dom.window.close()};
}
const settle=()=>new Promise(r=>setTimeout(r,0));const click=(p,selector)=>{const e=p.d.querySelector(selector);assert(e,'Missing '+selector);e.click();return e;};
const total=(p,m,b)=>p.sent.flatMap(s=>s.body.counts).filter(r=>r[0]===m&&r[1]===b).reduce((n,r)=>n+r[2],0);
test('10 banks have 16 unique questions, full translations and valid source/correct-answer identities',()=>{assert.equal(mods.length,10);const ids=new Set();for(const m of mods){assert.equal(m.questions.length,16);assert.equal(new Set(m.questions.map(q=>q.prompt.en)).size,16);for(const q of m.questions){assert(!ids.has(q.id));ids.add(q.id);for(const lang of ['en','ms','zh']){assert(q.prompt[lang]&&q.explanation[lang]);assert(q.options[lang].length>=3);assert.equal(q.options[lang].length,q.options.en.length);assert.equal(new Set(q.options[lang]).size,q.options[lang].length);}assert(q.correct>=0&&q.correct<q.options.en.length);assert(q.source);}}assert.equal(ids.size,160);});
test('Pinyin is tone-marked Chinese pronunciation only, excluding identifiers and numbers',()=>{for(const m of mods)for(const q of m.questions){assert(q.prompt.py);for(const p of [q.prompt.py,q.explanation.py,...q.options.py])assert(!/DF8B|CR200J|OCC|CTCS|\d/.test(p));}});
test('Fisher–Yates randomizes questions and answer positions; 2-module assessment is balanced',()=>{let n=17;const random=()=>((n=(n*1664525+1013904223)>>>0)/2**32);const runs=Array.from({length:20},()=>core.assessment([mods[0],mods[1]],random));for(const run of runs){assert.equal(run.length,16);assert.equal(new Set(run.map(x=>x.question.id)).size,16);assert.equal(run.filter(x=>x.module===mods[0].id).length,8);for(const x of run)assert.equal(new Set(x.order).size,x.question.options.en.length);}assert(new Set(runs.map(x=>x.map(q=>q.question.id).join())).size>1);assert(new Set(runs.flat().map(q=>q.order.indexOf(q.question.correct))).size>1);assert(!core.passed(11));assert(core.passed(12));});
test('Welcome preserves original photo and base styling, and Continue goes to gateway',async()=>{const p=await page('index.html');assert.equal(p.d.documentElement.lang,'ms');assert.equal(p.d.querySelector('#continue').getAttribute('href'),'gateway.html');assert.match(p.d.querySelector('.panel').textContent,/SELAMAT KEMBALI/);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'assets/railway-original.jpeg'))).digest('hex'),'fabd30d5c79262f9b968a38a86b06afb483b3223206c4be32439fb975ffa433f');click(p,'#information');assert(p.d.querySelector('#aboutDialog').open);click(p,'#closeDialog');assert(!p.d.querySelector('#aboutDialog').open);p.close();});
test('Five categories work; Coming Soon is empty; all 10 module cards exist',async()=>{const p=await page('gateway.html');assert.equal(p.d.querySelectorAll('[data-module]').length,10);for(const id of ['ebook','corridor','future','news','practical']){click(p,`[data-category="${id}"]`);assert.equal(p.d.querySelector('[aria-selected=true]').dataset.category,id);if(id==='future')assert.equal(p.d.querySelectorAll('[data-module]').length,0);}for(const m of mods){click(p,`[data-module="${m.id}"]`);assert.equal(p.d.querySelector(`[data-module="${m.id}"]`).getAttribute('aria-pressed'),'true');click(p,`[data-module="${m.id}"]`);}p.close();});
test('Language and Pinyin preserve category, selected modules and in-progress answers',async()=>{const p=await page('gateway.html');click(p,'[data-module="df8b_brake"]');click(p,'[data-lang="zh"]');assert(!p.d.body.classList.contains('with-pinyin'));click(p,'.pinyin-toggle');assert(p.d.body.classList.contains('with-pinyin'));assert.equal(p.d.querySelector('[data-module="df8b_brake"]').getAttribute('aria-pressed'),'true');click(p,'#start-quiz');const first=p.d.querySelector('#quiz-title').textContent;click(p,'[data-answer="0"]');assert(p.d.querySelector('.feedback'));click(p,'[data-quiz-lang="en"]');assert(p.d.querySelector('.feedback'));assert.equal(p.d.querySelectorAll('.answer-options button:disabled').length,p.d.querySelectorAll('.answer-options button').length);click(p,'[data-quiz-lang="zh"]');assert.equal(p.d.querySelector('#quiz-title').textContent,first);assert(p.d.body.classList.contains('with-pinyin'));click(p,'[data-exit-quiz]');assert(!p.d.querySelector('#quiz-dialog').open);p.close();});
test('Each module completes 16 answers, records PASS/latest result and preserves result across reload',async()=>{for(const m of mods){const p=await page('gateway.html');click(p,`[data-module="${m.id}"]`);click(p,'#start-quiz');for(let i=0;i<16;i++){assert.match(p.d.querySelector('.quiz-top').textContent,new RegExp(`${i+1} / 16`));click(p,'[data-answer="0"]');assert(p.d.querySelector('.feedback'));click(p,'[data-next]');}assert.match(p.d.querySelector('.score').textContent,/16 \/ 16/);const saved=p.w.localStorage.getItem('railway-study-latest');assert.equal(JSON.parse(saved).score,16);p.close();const restored=await page('gateway.html',{local:{'railway-study-latest':saved}});assert.match(restored.d.querySelector('#gateway-status').textContent,/16 \/ 16/);restored.close();}});
test('Wrong answers produce feedback and cannot double-score',async()=>{const p=await page('gateway.html');click(p,'[data-module="stabilizer"]');click(p,'#start-quiz');click(p,'[data-answer="1"]');assert(p.d.querySelector('.incorrect'));assert(p.d.querySelector('.correct'));click(p,'[data-answer="0"]');assert.match(p.d.querySelector('.quiz-top').textContent,/Markah\s*0/);p.close();});
test('Routing links cover Home, Journey, Field and Lab with valid local portfolio anchors',async()=>{const p=await page('gateway.html'),html=fs.readFileSync(path.join(root,'portfolio.html'),'utf8');for(const id of ['home','journey','experience','lab']){click(p,`[data-mode="${id}"]`);assert.equal(p.d.querySelector('#enter-portfolio').getAttribute('href'),'portfolio.html#'+id);assert(html.includes(`id="${id}"`));}p.close();});
test('Portfolio has all eight destinations, no old Sites redirect, persisted Chinese/Pinyin and working menu',async()=>{const p=await page('portfolio.html#lab',{local:{'railway-language':'zh','railway-pinyin':'on'}});assert.equal(p.d.documentElement.lang,'zh-Hans');assert(p.d.body.classList.contains('with-pinyin'));for(const id of ['home','journey','experience','lab','activities','about','contact','resume'])assert(p.d.querySelector('main>#'+id));assert(!p.d.querySelector('meta[http-equiv=refresh]'));assert(!p.d.body.innerHTML.includes('chatgpt.site'));click(p,'.menu-button');assert.equal(p.d.querySelector('.menu-button').getAttribute('aria-expanded'),'true');click(p,'[data-lang="en"]');assert.equal(p.w.location.hash,'#lab');assert(p.d.querySelector('.pinyin-toggle').hidden);p.close();});
test('Ordered Welcome→Gateway→Portfolio funnel continues across pages with a fixed non-identifying stage',async()=>{let p=await page('index.html');click(p,'#continue');await settle();const marker=p.w.sessionStorage.getItem('railway-analytics-next-stage');assert.equal(marker,'modes');assert.equal(total(p,'funnel','welcome'),1);p.close();p=await page('gateway.html',{session:{'railway-analytics-next-stage':marker}});assert.equal(total(p,'funnel','modes'),1);click(p,'#enter-portfolio');await settle();const next=p.w.sessionStorage.getItem('railway-analytics-next-stage');assert.equal(next,'portfolio');p.close();p=await page('portfolio.html#experience',{session:{'railway-analytics-next-stage':next}});assert.equal(total(p,'funnel','portfolio'),1);assert.equal(total(p,'view','experience'),1);assert.equal(p.w.sessionStorage.getItem('railway-analytics-next-stage'),null);p.close();});
test('Production-safe pending extension excludes unsupported buckets but retains original language/click metrics',async()=>{const p=await page('gateway.html');click(p,'[data-category="news"]');click(p,'[data-lang="zh"]');click(p,'.pinyin-toggle');click(p,'[data-mode="lab"]');await settle();assert.equal(total(p,'category','news'),0);assert.equal(total(p,'language','中文'),1);assert.equal(total(p,'pinyin','ON'),1);assert.equal(total(p,'learning_mode','lab'),1);assert(p.sent.every(s=>s.opts.credentials==='omit'&&s.opts.referrerPolicy==='no-referrer'));p.close();});
test('Staged analytics captures category, module and quiz events with no answers or identity payload',async()=>{const p=await page('gateway.html',{extension:true});click(p,'[data-category="practical"]');click(p,'[data-module="gmc48"]');click(p,'#start-quiz');for(let i=0;i<16;i++){click(p,'[data-answer="0"]');click(p,'[data-next]');}await settle();assert.equal(total(p,'category','practical'),1);assert.equal(total(p,'module','gmc48'),1);assert.equal(total(p,'quiz_start','all'),1);assert.equal(total(p,'quiz_complete','all'),1);for(const s of p.sent){assert.deepEqual(Object.keys(s.body),['counts']);assert(!/name|email|phone|login|latitude|longitude|answer|score/.test(s.opts.body));}p.close();});
test('DNT disables original and migration event emission',async()=>{const p=await page('gateway.html',{extension:true,dnt:true});click(p,'[data-category="news"]');await settle();assert.equal(p.sent.length,0);p.close();});
test('All local links, scripts, styles and source anchors resolve',()=>{for(const file of ['index.html','gateway.html','portfolio.html']){const dom=new JSDOM(fs.readFileSync(path.join(root,file),'utf8'));for(const el of dom.window.document.querySelectorAll('[href],[src]')){const url=el.getAttribute('href')||el.getAttribute('src');if(/^(https?:|mailto:|data:)/.test(url))continue;const [p,hash]=url.split('#');const target=path.join(root,p||file);assert(fs.existsSync(target),`${file}: ${url}`);if(hash&&target.endsWith('.html'))assert(fs.readFileSync(target,'utf8').includes(`id="${hash}"`),url);}dom.window.close();}});
test('Responsive CSS contracts cover narrow phones, tablets, split-screen and safe viewports',()=>{const css=fs.readFileSync(path.join(root,'assets/gateway.css'),'utf8');assert(css.includes('repeat(2,minmax(0,1fr))'));assert(css.includes('max-width:719px'));assert(css.includes('grid-template-columns:1fr'));assert(css.includes('100svh'));assert(css.includes('safe-area-inset'));assert(css.includes('overflow-y:auto'));assert(!css.includes(':hover'));});
