import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from './worker.mjs';
const origin='https://khairuladamm1993-web.github.io';
function db(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../original/drizzle/0000_loose_northstar.sql',import.meta.url),'utf8'));return {sql,prepare(query){return{bind(...args){return{query,args};}}},async batch(rows){sql.exec('BEGIN');try{for(const r of rows)sql.prepare(r.query).run(...r.args);sql.exec('COMMIT');}catch(e){sql.exec('ROLLBACK');throw e;}}};}
function request({method='POST',from=origin,path='/api/anonymous-counts',headers={},body={counts:[['visits','all',1]]}}={}){return new Request('https://example.workers.dev'+path,{method,headers:{origin:from,'content-type':'application/json',...headers},...(method==='POST'?{body:JSON.stringify(body)}:{})});}
test('allowed cross-origin events reach original collector and persist aggregates',async()=>{const DB=db();const req=request({headers:{'sec-fetch-site':'cross-site',cookie:'identity=NEVER',authorization:'Bearer NEVER'}});Object.defineProperty(req,'cf',{value:{country:'MY',get city(){throw Error('Forbidden');}}});const r=await worker.fetch(req,{DB});assert.equal(r.status,204);assert.equal(r.headers.get('Access-Control-Allow-Origin'),origin);assert.equal(r.headers.get('Access-Control-Allow-Credentials'),null);assert.equal(r.headers.get('Permissions-Policy'),'geolocation=()');const rows=DB.sql.prepare('SELECT * FROM anonymous_daily_totals').all();assert.equal(rows.find(r=>r.metric==='visits').value,1);assert.equal(rows.find(r=>r.metric==='country').bucket,'MY');assert(!JSON.stringify(rows).includes('NEVER'));DB.sql.close();});
test('CORS rejects other origins, unknown headers, methods and read routes',async()=>{assert.equal((await worker.fetch(request({from:'https://evil.test'}),{})).status,403);assert.equal((await worker.fetch(request({from:'null'}),{})).status,403);assert.equal((await worker.fetch(request({method:'GET'}),{})).status,405);assert.equal((await worker.fetch(request({path:'/dashboard'}),{})).status,404);assert.equal((await worker.fetch(request({method:'OPTIONS',headers:{'Access-Control-Request-Method':'POST','Access-Control-Request-Headers':'authorization'}}),{})).status,403);const r=await worker.fetch(request({method:'OPTIONS',headers:{'Access-Control-Request-Method':'POST','Access-Control-Request-Headers':'content-type'}}),{});assert.equal(r.status,204);assert.equal(r.headers.get('Access-Control-Allow-Methods'),'POST');});
test('original validation, privacy opt-out and no-database failure remain enforced',async()=>{const DB=db();assert.equal((await worker.fetch(request({body:{counts:[['visits','all',1]],email:'bad'}}),{DB})).status,400);assert.equal((await worker.fetch(request({headers:{DNT:'1'}}),{DB})).status,204);assert.equal((await worker.fetch(request({headers:{'Sec-GPC':'1'}}),{DB})).status,204);assert.equal(DB.sql.prepare('SELECT count(*) n FROM anonymous_daily_totals').get().n,0);assert.equal((await worker.fetch(request(),{})).status,503);DB.sql.close();});
test('country absence does not block writes; dashboard queries load aggregates',async()=>{const DB=db();const req=request();Object.defineProperty(req,'cf',{get(){throw Error('metadata unavailable');}});assert.equal((await worker.fetch(req,{DB})).status,204);assert.equal(DB.sql.prepare("SELECT count(*) n FROM anonymous_daily_totals WHERE metric='country'").get().n,0);const queries=readFileSync(new URL('./dashboard.sql',import.meta.url),'utf8').split(';').filter(s=>s.trim());for(const query of queries)assert(Array.isArray(DB.sql.prepare(query).all()));assert.equal(DB.sql.prepare('SELECT sum(value) n FROM anonymous_daily_totals').get().n,1);DB.sql.close();});
